language: python
python:
  - "2.7"
  - "3.5"
  - "3.6"
  - "3.7"  
env:
  - DJANGO_DRF=django111-drf37
# command to install dependencies
install: "pip install tox"
# command to run tests
script:
  - export TOX_ENV=py${TRAVIS_PYTHON_VERSION/./}-${DJANGO_DRF}
  - tox -r -e "$TOX_ENV"
matrix:
  include:
    - python: "2.7"
      env: DJANGO_DRF="django18-drf33"
    - python: "2.7"
      env: DJANGO_DRF="django18-drf34"
    - python: "2.7"
      env: DJANGO_DRF="django18-drf35"
    - python: "2.7"
      env: DJANGO_DRF="django18-drf36"
    - python: "2.7"
      env: DJANGO_DRF="django19-drf33"
    - python: "2.7"
      env: DJANGO_DRF="django19-drf34"
    - python: "2.7"
      env: DJANGO_DRF="django19-drf35"
    - python: "2.7"
      env: DJANGO_DRF="django19-drf36"
    - python: "2.7"
      env: DJANGO_DRF="django110-drf34"
    - python: "2.7"
      env: DJANGO_DRF="django110-drf35"
    - python: "2.7"
      env: DJANGO_DRF="django110-drf36"
    - python: "2.7"
      env: DJANGO_DRF="django110-drf37"
    - python: "2.7"
      env: DJANGO_DRF="django111-drf35"
    - python: "2.7"
      env: DJANGO_DRF="django111-drf36"
    - python: "2.7"
      env: DJANGO_DRF="django111-drf37" 
    - python: "3.5"
      env: DJANGO_DRF="django18-drf33"
    - python: "3.5"
      env: DJANGO_DRF="django18-drf34"
    - python: "3.5"
      env: DJANGO_DRF="django18-drf35"
    - python: "3.5"
      env: DJANGO_DRF="django18-drf36"
    - python: "3.5"
      env: DJANGO_DRF="django19-drf33"
    - python: "3.5"
      env: DJANGO_DRF="django19-drf34"
    - python: "3.5"
      env: DJANGO_DRF="django19-drf35"
    - python: "3.5"
      env: DJANGO_DRF="django19-drf36"
    - python: "3.5"
      env: DJANGO_DRF="django110-drf34"
    - python: "3.5"
      env: DJANGO_DRF="django110-drf35"
    - python: "3.5"
      env: DJANGO_DRF="django110-drf36"
    - python: "3.5"
      env: DJANGO_DRF="django110-drf37"
    - python: "3.5"
      env: DJANGO_DRF="django111-drf34"
    - python: "3.5"
      env: DJANGO_DRF="django111-drf35"
    - python: "3.5"
      env: DJANGO_DRF="django111-drf36"
    - python: "3.5"
      env: DJANGO_DRF="django111-drf37"
    - python: "3.5"
      env: DJANGO_DRF="django20-drf37"
    - python: "3.5"
      env: DJANGO_DRF="django20-drf38"
    - python: "3.5"
      env: DJANGO_DRF="django20-drf39"
    # - python: "3.5"
    # - env: DJANGO_DRF="django21-drf37"
    - python: "3.6"
      env: DJANGO_DRF="django18-drf33"
    - python: "3.6"
      env: DJANGO_DRF="django18-drf34"
    - python: "3.6"
      env: DJANGO_DRF="django18-drf35"
    - python: "3.6"
      env: DJANGO_DRF="django18-drf36"
    - python: "3.6"
      env: DJANGO_DRF="django19-drf33"
    - python: "3.6"
      env: DJANGO_DRF="django19-drf34"
    - python: "3.6"
      env: DJANGO_DRF="django19-drf35"
    - python: "3.6"
      env: DJANGO_DRF="django19-drf36"
    - python: "3.6"
      env: DJANGO_DRF="django110-drf34"
    - python: "3.6"
      env: DJANGO_DRF="django110-drf35"
    - python: "3.6"
      env: DJANGO_DRF="django110-drf36"
    - python: "3.6"
      env: DJANGO_DRF="django110-drf37"
    - python: "3.6"
      env: DJANGO_DRF="django111-drf34"
    - python: "3.6"
      env: DJANGO_DRF="django111-drf35"
    - python: "3.6"
      env: DJANGO_DRF="django111-drf36"
    - python: "3.6"
      env: DJANGO_DRF="django111-drf37"
    - python: "3.6"
      env: DJANGO_DRF="django20-drf37"
    - python: "3.6"
      env: DJANGO_DRF="django20-drf38"
    - python: "3.6"
      env: DJANGO_DRF="django20-drf39"
    - python: "3.6"
      env: DJANGO_DRF="django21-drf37"
    - python: "3.6"
      env: DJANGO_DRF="django21-drf38"
    - python: "3.6"
      env: DJANGO_DRF="django21-drf39"
    - python: "3.6"
      env: DJANGO_DRF="django22-drf37"
    - python: "3.6"
      env: DJANGO_DRF="django22-drf38"
    - python: "3.6"
      env: DJANGO_DRF="django22-drf39"
    - python: "3.7"
      env: DJANGO_DRF="django20-drf37"
    - python: "3.7"
      env: DJANGO_DRF="django20-drf38"
    - python: "3.7"
      env: DJANGO_DRF="django20-drf39"
    - python: "3.7"
      env: DJANGO_DRF="django21-drf37"
    - python: "3.7"
      env: DJANGO_DRF="django21-drf38"
    - python: "3.7"
      env: DJANGO_DRF="django21-drf39"
    - python: "3.7"
      env: DJANGO_DRF="django22-drf37"
    - python: "3.7"
      env: DJANGO_DRF="django22-drf38"
    - python: "3.7"
      env: DJANGO_DRF="django22-drf39"
  allow_failures:
    - python: "3.6"
      env: DJANGO_DRF="django20-drfmaster"
    # - python: "3.6"
    # - env: DJANGO_DRF="django21-drfmaster"
    - python: "3.7"
      env: DJANGO_DRF="djangomaster-drf38"
    - python: "3.7"
      env: DJANGO_DRF="djangomaster-drfmaster"
    - python: "3.6"
      env: DJANGO_DRF="django20-drfmaster"
    - python: "3.6"
      env: DJANGO_DRF="djangomaster-drf38"
    - python: "3.6"
      env: DJANGO_DRF="djangomaster-drfmaster"

