language: python
# command to install dependencies
install: "pip install tox"
# command to run tests
script:
  - export TOX_ENV=py${TRAVIS_PYTHON_VERSION/./}-${DJANGO_DRF}
  - tox -r -e "$TOX_ENV"
matrix:
  include:
    - python: "3.5"
      env: DJANGO_DRF="django20-drf38"
    - python: "3.5"
      env: DJANGO_DRF="django20-drf39"
    - python: "3.5"
      env: DJANGO_DRF="django21-drf38"
    - python: "3.5"
      env: DJANGO_DRF="django21-drf39"
    - python: "3.6"
      env: DJANGO_DRF="django20-drf38"
    - python: "3.6"
      env: DJANGO_DRF="django20-drf39"
    - python: "3.6"
      env: DJANGO_DRF="django21-drf38"
    - python: "3.6"
      env: DJANGO_DRF="django21-drf39"
    - python: "3.6"
      env: DJANGO_DRF="django22-drf38"
    - python: "3.6"
      env: DJANGO_DRF="django22-drf39"
    - python: "3.6"
      env: DJANGO_DRF="django22-drfmaster"
    - python: "3.6"
      env: DJANGO_DRF="djangomaster-drf39"
    - python: "3.6"
      env: DJANGO_DRF="djangomaster-drfmaster"
    - python: "3.7"
      env: DJANGO_DRF="django20-drf38"
    - python: "3.7"
      env: DJANGO_DRF="django20-drf39"
    - python: "3.7"
      env: DJANGO_DRF="django21-drf38"
    - python: "3.7"
      env: DJANGO_DRF="django21-drf39"
    - python: "3.7"
      env: DJANGO_DRF="django22-drf38"
    - python: "3.7"
      env: DJANGO_DRF="django22-drf39"
  allow_failures:
    - python: "3.6"
      env: DJANGO_DRF="django22-drfmaster"
    - python: "3.6"
      env: DJANGO_DRF="djangomaster-drf39"
    - python: "3.6"
      env: DJANGO_DRF="djangomaster-drfmaster"
