site_name: DRF-schema-adapter documentation
repo_url: https://github.com/drf-forms/drf-schema-adapter
pages:
  - Home: index.md
  - 'DRF-auto-endpoint':
    - 'DRF-auto-endpoint': drf_auto_endpoint/index.md
    - 'Endpoint': drf_auto_endpoint/endpoint.md
    - 'Metadata': drf_auto_endpoint/metadata.md
  - 'Export-app': export_app/index.md
  - 'Cookbooks':
    - 'Creating endpoints from models': cookbooks/endpoints.md
  - License: LICENSE.md
  - 'Code of conduct': COC.md
